name = "recohub"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "recohub-db"
database_id = "bee123f1-9787-4f4d-8347-44c22306a386"
