import { readFileSync, writeFileSync } from 'node:fs'

const migrate = readFileSync('db/migrate.sql', 'utf8')
const seed = readFileSync('db/seed.sql', 'utf8')

const out = `// Auto-generated by scripts/generate-schema.js — DO NOT EDIT
export const MIGRATE_SQL = ${JSON.stringify(migrate)}
export const SEED_SQL = ${JSON.stringify(seed)}
`

writeFileSync('functions/lib/dbSchema.ts', out)
